### ISSUE TITLE
Docs contains invalid information

### ISSUE THREAD

**Issue by FoggyFinder** [tforkmann/Fumble#1]
![fumbleDoc](https://user-images.githubusercontent.com/16510738/86518338-d984e500-be39-11ea-9c9d-5183cc181888.jpg)

^ Current page is confusing:

The page is almost empty and that even worse - contains wrong information:

> Thin F# API for Sqlite for easy data access to ms sql server with functional seasoning on top

Project is not about MSSQL

Also it says that NuGet version is 0.6.3. though is is 0.1 so far.

**Comment by tforkmann** [comment]
Hi there,
sorry didn't had much time to work on the docs yet.

Just fixed the docs main page.
Will add some more docs in the next week.
