### ISSUE TITLE
Add rollForward to the global.json config

### ISSUE THREAD

**Issue by FoggyFinder** [tforkmann/Fumble#2]
Currently exactly the same version of .net core as defined in the global.json is required.

> The roll-forward policy to use when selecting an SDK version, either as a fallback when a specific SDK version is missing or as a directive to use a higher version.

https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#rollforward

With, for example, `rollforward = feature` those who have newer version of SDK than one that is specified will be able to load project without error.

**Comment by tforkmann** [comment]
Hi there,
added rollForward now to the global.json.
Does that work for you now?

**Comment by FoggyFinder** [comment]
Yep, thanks
