### ISSUE TITLE
SqliteRowReader float  only parses float32

### ISSUE THREAD

**Issue by wavewizard** [tforkmann/Fumble#24]
Example type 
Type T = {Width t : float}

...
|> Sqlite.execute (fun read -> { {Width = read.float "Width"}

gives 

Type constraint mismatch. The type 
    'float32'    
is not compatible with type
    'float'

**Comment by tforkmann** [comment]
Hi @wavewizard,

Thanks for your issue.
I will tryi to fix that by the end of day.

Cheers,
Tim

**Comment by wavewizard** [comment]
Thank you for the library,  I like the design  and its simplicity. Will be using it

**Comment by tforkmann** [comment]
Actually it is already implemented.
You have to use ``read.double`` then you will read the correct type of float.

Microsoft.Data.Sqlite is using double as well therefore I named it the same way.

Let me know if that works for you

**Comment by wavewizard** [comment]
It works

what do you think  implementing  changing  SqlightRowReader.float to float32 and adding  float  that parses double?  
I can create a PR for that if you want.
Cheers

**Comment by tforkmann** [comment]
Yes, that sounds good.
Feel free to create a PR for that.
If not I will do it tonight.
Cheers

**Comment by tforkmann** [comment]
Implemented and released. Let me know if you need something else. Cheers
