### ISSUE TITLE
F# codegen for Fumble

### ISSUE THREAD

**Issue by kaashyapan** [tforkmann/Fumble#27]
I've published a package that produces F# code from sql.
https://github.com/kaashyapan/sqlc-gen-fsharp

The Sqlite version wraps Fumble.
Please spare a thought if you decide to break something.

P.s - I'd also be great if you can rename `type Sqlite` to `type Sql`. `module Sqlite` to `type Sql`.
That would align this with Npgsql.FSharp and the produced code would look identical.

**Comment by tforkmann** [comment]
@kaashyapan Wow that is great! The renaming shouldnt be a problem. Trying to release a new version soon.

**Comment by tforkmann** [comment]
@kaashyapan  Just released a new version please have a look if that is working for you now.

**Comment by kaashyapan** [comment]
Thanks for the quick response. I missed mentioning one rename. If you can merge and release a new version that would be great.

**Comment by tforkmann** [comment]
Done!
