### ISSUE TITLE
Remove Microsoft.Data.SqlClient dependency?

### ISSUE THREAD

**Issue by jgidlow** [tforkmann/Fumble#29]
Is Microsoft.Data.SqlClient used by Fumble in some way I'm not understanding or would it perhaps be possible to remove since it brings in so many transitive dependencies? As far as I can tell Fumble only uses code from Microsoft.Data.Sqlite and it seems to compile just fine without Microsoft.Data.SqlClient if I paket remove it.

**Comment by tforkmann** [comment]
Good catch!

I removed the dependency and released a new version.

Hope that helps!

Cheers,
Tim

**Comment by jgidlow** [comment]
It works great! Thank you!
