### ISSUE TITLE
Sqlite table: `typeName` parameter is ignored

### ISSUE THREAD

**Issue by FoggyFinder** [tforkmann/Fumble#3]
https://github.com/tforkmann/Fumble/blob/53bb80ae729765ced4033f224cba2bdbf71028c0/src/Fumble/Sqlite.fs#L80-L81

Looks like either another ctor of `SqliteParameter` should be used or `typeName` can be removed totally.

Also, unclear why it is marked as `inline`.

**Comment by tforkmann** [comment]
Hi there,
I got rid of the typeName and the inline.

Thanks for the hint!
